# Basic Python

## 1. Split this string

In [22]:
s = "Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [36]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {}".format(planet,diameter))

The diameter of Earth is 12742

## 3. In this nest dictionary grab the word "hello"

In [35]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello

# Numpy

In [34]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [32]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [33]:
array1=np.ones(10)*5
print(array1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 20 to 35

In [29]:
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [28]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [27]:
import pandas as pd
data=[['prarthana',10],['prrapti',28],['aathish',6]]
df=pd.DataFrame(data,columns=['name','age'])
print(df)

        name  age
0  prarthana   10
1    prrapti   28
2    aathish    6

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [26]:
date=pd.date_range(start='1/1/2023',end='10/02/2023')
print(date)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [25]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['num','word','number'])
print(df)

   num word  number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24